apiVersion: v1
kind: Pod
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v0.16.0
      command:
        - /bin/cat
      imagePullPolicy: Always
      resources:
        requests:
          memory: "1Gi"
          cpu: "125m"
        limits:
          memory: "1Gi"
