apiVersion: batch/v1
kind: Job
metadata:
  name: hellok8stest
spec:
  backoffLimit: 6 # number of retries before throwing error
  activeDeadlineSeconds: 2400 # time to allow job to run
  template:
    metadata:
      labels:
        app: hellok8stest
        tier: job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: hellok8stest
          image: docker.io/rlkamradt/hellok8stest:latest
